"""Migration name

Revision ID: 07906fcb7035
Revises: 6b3dc5998715
Create Date: 2023-11-29 18:53:55.688018

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "07906fcb7035"
down_revision: Union[str, None] = "6b3dc5998715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
