"""Migration name

Revision ID: 096a35c3e969
Revises: 1188b3aa4557
Create Date: 2023-12-04 16:41:37.628690

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "096a35c3e969"
down_revision: Union[str, None] = "1188b3aa4557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
