"""Migration name

Revision ID: 0c0417c21bd6
Revises: 60c1f49a39b5
Create Date: 2023-11-30 22:41:36.481376

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0c0417c21bd6"
down_revision: Union[str, None] = "60c1f49a39b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
