"""Migration name

Revision ID: 1188b3aa4557
Revises: 281fedfc118f
Create Date: 2023-12-04 16:37:05.163710

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1188b3aa4557"
down_revision: Union[str, None] = "281fedfc118f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
