"""Migration name

Revision ID: 11a5ca5d31fc
Revises: 794434dd7488
Create Date: 2023-11-26 16:52:58.777768

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "11a5ca5d31fc"
down_revision: Union[str, None] = "794434dd7488"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
