"""Migration name

Revision ID: 1384f3c71510
Revises: 420ea675cd76
Create Date: 2023-11-29 13:52:29.215344

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1384f3c71510"
down_revision: Union[str, None] = "420ea675cd76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
