"""Migration name

Revision ID: 14288a970bdc
Revises: 85696fee322f
Create Date: 2023-12-01 04:40:55.741421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14288a970bdc"
down_revision: Union[str, None] = "85696fee322f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "productdealers",
        "status",
        existing_type=sa.BOOLEAN(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "productdealers",
        "status",
        existing_type=sa.String(),
        type_=sa.BOOLEAN(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
