"""Migration name

Revision ID: 42a781f026b3
Revises: 096a35c3e969
Create Date: 2023-12-04 16:47:27.762511

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "42a781f026b3"
down_revision: Union[str, None] = "096a35c3e969"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
