"""Migration name

Revision ID: 45a75be15e68
Revises: 9e653f2c4931
Create Date: 2023-11-27 13:59:34.885500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45a75be15e68"
down_revision: Union[str, None] = "9e653f2c4931"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dealerprices", "date", existing_type=sa.DATE(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dealerprices", "date", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###
