"""Migration name

Revision ID: 45b6a86b0d5b
Revises: b5981d1ff3df
Create Date: 2023-12-04 16:55:31.416233

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "45b6a86b0d5b"
down_revision: Union[str, None] = "b5981d1ff3df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
