"""Migration name

Revision ID: 4e3d1fd66a96
Revises: 1384f3c71510
Create Date: 2023-11-29 13:55:12.277631

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "4e3d1fd66a96"
down_revision: Union[str, None] = "1384f3c71510"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
