"""Migration name

Revision ID: 5134ad9562ae
Revises: 58e7455dce83
Create Date: 2023-11-28 19:25:06.538737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5134ad9562ae"
down_revision: Union[str, None] = "58e7455dce83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productdealerkey",
        sa.Column("key", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("dealer_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_id"],
            ["dealers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["key"],
            ["dealerprices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "product_id", "dealer_id"),
    )
    op.create_index(
        op.f("ix_productdealerkey_id"),
        "productdealerkey",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_productdealerkey_id"), table_name="productdealerkey"
    )
    op.drop_table("productdealerkey")
    # ### end Alembic commands ###
