"""Migration name

Revision ID: 58e7455dce83
Revises: 74286c925559
Create Date: 2023-11-28 17:36:26.376907

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "58e7455dce83"
down_revision: Union[str, None] = "74286c925559"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "dealerprices_dealer_id_product_key_key",
        "dealerprices",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "dealerprices_dealer_id_product_key_key",
        "dealerprices",
        ["dealer_id", "product_key"],
    )
    # ### end Alembic commands ###
