"""Migration name

Revision ID: 60c1f49a39b5
Revises: df21fe57ee5e
Create Date: 2023-11-30 20:39:14.313313

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "60c1f49a39b5"
down_revision: Union[str, None] = "df21fe57ee5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
