"""Migration name

Revision ID: 6b0a572e497a
Revises: d8a37fd8ef2c
Create Date: 2023-12-04 17:17:34.373148

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6b0a572e497a"
down_revision: Union[str, None] = "d8a37fd8ef2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
