"""Migration name

Revision ID: 85696fee322f
Revises: 750585164ec0
Create Date: 2023-11-30 23:52:21.263109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85696fee322f"
down_revision: Union[str, None] = "750585164ec0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "productdealers", "key", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "productdealers",
        "dealer_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "productdealers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "user",
        "registered_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "registered_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "productdealers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "productdealers",
        "dealer_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "productdealers", "key", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
