"""Migration name

Revision ID: 8defa0608583
Revises: 017866593168
Create Date: 2023-11-30 16:20:12.293252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8defa0608583"
down_revision: Union[str, None] = "017866593168"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_productdealerlaters_id", table_name="productdealerlaters"
    )
    op.drop_table("productdealerlaters")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productdealerlaters",
        sa.Column("key", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["key"], ["dealerprices.id"], name="productdealerlaters_key_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="productdealerlaters_pkey"),
    )
    op.create_index(
        "ix_productdealerlaters_id",
        "productdealerlaters",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###
