"""Migration name

Revision ID: 905751d6c859
Revises: 02bd38eced6f
Create Date: 2023-11-30 13:37:01.848586

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "905751d6c859"
down_revision: Union[str, None] = "02bd38eced6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
