"""Migration name

Revision ID: 9e653f2c4931
Revises: 7d5e98ce514d
Create Date: 2023-11-26 22:34:31.033631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e653f2c4931"
down_revision: Union[str, None] = "7d5e98ce514d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dealerprices", sa.Column("mapped", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dealerprices", "mapped")
    # ### end Alembic commands ###
