"""Migration name

Revision ID: b5981d1ff3df
Revises: 42a781f026b3
Create Date: 2023-12-04 16:53:21.182218

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b5981d1ff3df"
down_revision: Union[str, None] = "42a781f026b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
