"""Migration name

Revision ID: b5b6d10a57d9
Revises: 
Create Date: 2023-12-04 19:27:29.098764

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5b6d10a57d9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dealers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dealers_id"), "dealers", ["id"], unique=False)
    op.create_table(
        "modelvectors",
        sa.Column("value", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modelvectors_id"), "modelvectors", ["id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("article", sa.String(), nullable=True),
        sa.Column("ean_13", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("recommended_price", sa.Float(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("ozon_name", sa.String(), nullable=True),
        sa.Column("name_1c", sa.String(), nullable=True),
        sa.Column("wb_name", sa.String(), nullable=True),
        sa.Column("ozon_article", sa.String(), nullable=True),
        sa.Column("wb_article", sa.String(), nullable=True),
        sa.Column("ym_article", sa.String(), nullable=True),
        sa.Column("wb_article_td", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article"),
    )
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("registered_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "dealerprices",
        sa.Column("product_key", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("product_url", sa.String(), nullable=True),
        sa.Column("product_name", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("dealer_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_id"],
            ["dealers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dealerprices_id"), "dealerprices", ["id"], unique=False
    )
    op.create_table(
        "productdealers",
        sa.Column("key", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("dealer_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('matched', 'not matched', 'deferred')",
            name="check_status",
        ),
        sa.ForeignKeyConstraint(
            ["dealer_id"],
            ["dealers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["key"],
            ["dealerprices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("key", "product_id", "dealer_id"),
    )
    op.create_index(
        op.f("ix_productdealers_id"), "productdealers", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_productdealers_id"), table_name="productdealers")
    op.drop_table("productdealers")
    op.drop_index(op.f("ix_dealerprices_id"), table_name="dealerprices")
    op.drop_table("dealerprices")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_modelvectors_id"), table_name="modelvectors")
    op.drop_table("modelvectors")
    op.drop_index(op.f("ix_dealers_id"), table_name="dealers")
    op.drop_table("dealers")
    # ### end Alembic commands ###
