"""Migration name

Revision ID: cc3712ec04c5
Revises: 07906fcb7035
Create Date: 2023-11-29 19:19:32.796762

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cc3712ec04c5"
down_revision: Union[str, None] = "07906fcb7035"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
