"""Migration name

Revision ID: d8a37fd8ef2c
Revises: 45b6a86b0d5b
Create Date: 2023-12-04 16:56:51.391307

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d8a37fd8ef2c"
down_revision: Union[str, None] = "45b6a86b0d5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
