"""Migration name

Revision ID: dc404083dc40
Revises: 8defa0608583
Create Date: 2023-11-30 16:21:22.185030

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "dc404083dc40"
down_revision: Union[str, None] = "8defa0608583"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
