"""Migration name

Revision ID: df21fe57ee5e
Revises: fd89718cf098
Create Date: 2023-11-30 19:58:56.062642

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "df21fe57ee5e"
down_revision: Union[str, None] = "fd89718cf098"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
