"""Migration name

Revision ID: e407c6d06db3
Revises: 8faf41335958
Create Date: 2023-12-04 22:40:03.340701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e407c6d06db3"
down_revision: Union[str, None] = "8faf41335958"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productsmappeds",
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("dealerprice_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealerprice_id"],
            ["dealerprices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dealerprice_id"),
    )
    op.create_index(
        op.f("ix_productsmappeds_id"), "productsmappeds", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_productsmappeds_id"), table_name="productsmappeds")
    op.drop_table("productsmappeds")
    # ### end Alembic commands ###
