"""Migration name

Revision ID: fd89718cf098
Revises: dc404083dc40
Create Date: 2023-11-30 19:57:03.038908

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fd89718cf098"
down_revision: Union[str, None] = "dc404083dc40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
