"""Migration name

Revision ID: 9deccf28c8e0
Revises: e407c6d06db3
Create Date: 2023-12-04 22:49:13.030959

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9deccf28c8e0"
down_revision: Union[str, None] = "e407c6d06db3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "productsmappeds_dealerprice_id_key", "productsmappeds", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "productsmappeds_dealerprice_id_key",
        "productsmappeds",
        ["dealerprice_id"],
    )
    # ### end Alembic commands ###
